 CREATE TABLE "GCG_5654_AUDIT" (
 "ORDER_NO" CHAR(7) NOT NULL,
 "RECORD_NO" CHAR(4) NOT NULL,
 "ORIG_PROM_DT" CHAR(8) NOT NULL,
 "NEW_PROM_DT" CHAR(8) NOT NULL,
 "CHNG_COUNT" SMALLINT NOT NULL,
 "CHG_USER" CHAR(8) NOT NULL,
 "CHG_REASON" LONGVARCHAR,
 "DATE_CHNG" DATE );
 
 
